version: '3.8'

services:
  db:
    image: postgres:15
    container_name: camunda_db
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  camunda:
    image: camunda/camunda-bpm-platform:run-7.23.0
    container_name: camunda
    depends_on:
      - db
    ports:
      - "8090:8080"
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://db:5432/camunda
      DB_USERNAME: camunda
      DB_PASSWORD: camunda
      WAIT_FOR: db:5432               # ждать БД при старте
      JAVA_OPTS: "-Xms512m -Xmx2g"    # тюнинг памяти
    networks:
      - app_network
volumes:
  pgdata:

networks:
  app_network:
    external: true
