services:
  order_postgres:
    container_name: order_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - '5435:5432'
    volumes:
      - pgdata_order:/var/lib/postgresql/data
    expose:
      - '5432'
    networks:
      - app_network

  order_service_backend:
    image: lunghr/blps-3-order:latest
    container_name: order_service_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8084:8080'
    depends_on:
      order_postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - CAMUNDA_REST_URL=http://camunda:8080/engine-rest
      - TOPIC_NAME=cancel-order
      - LOCK_DURATION=30000
      - ASYNC_RESPONSE_TIMEOUT=10000
    networks:
      - app_network


networks:
  app_network:
    external: true

volumes:
  pgdata_order: { }
