services:
  bank_postgres:
    container_name: bank_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - '5437:5432'
    volumes:
      - pgdata_bank:/var/lib/postgresql/data
    expose:
      - '5432'
    networks:
      - app_network

  bank_service_backend:
    image: lunghr/blps-3-bank:latest
    container_name: bank_service_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8086:8080'
    depends_on:
      bank_postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app_network


networks:
  app_network:
    external: true

volumes:
  pgdata_bank: { }
